micronaut:
  application:
    name: valoriza
---
#tag::security[]
micronaut:
  security:
    authentication: bearer # <1>
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Im1hdGhldXMiLCJpYXQiOjE1MTYyMzkwMjJ9.1tOLcMHR3DSgrf-SfF8ZvvzH6R-RK7BX0WjGRYjjFYk' # <2>
#end::security[]